# Generated by Django 5.0.7 on 2024-07-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_fruit_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'ordering': ['fruit_name'], 'permissions': [('can_view', 'Can view the model'), ('can_edit', 'Can edit the model')], 'verbose_name': 'My Fruit Model'},
        ),
        migrations.AlterUniqueTogether(
            name='fruit',
            unique_together={('fruit_name', 'price')},
        ),
    ]
