# Generated by Django 5.0.6 on 2024-10-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mobile_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
    ]
