# Generated by Django 5.0.6 on 2024-10-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_brand_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name',)},
        ),
    ]
