# Generated by Django 5.0.6 on 2024-10-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mobile_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobile',
            unique_together={('brand_name', 'model_name')},
        ),
    ]
