# Generated by Django 5.0.7 on 2024-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('manufacturing_date', models.DateField()),
                ('description', models.TextField()),
                ('is_fresh', models.BooleanField(default=False)),
            ],
        ),
    ]
