# Generated by Django 5.0.7 on 2024-07-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fruit',
            table='MyFruit',
        ),
    ]
