# Generated by Django 5.0.7 on 2024-07-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_fruit_options_alter_fruit_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'ordering': ['fruit_name'], 'verbose_name': 'My Fruit Model'},
        ),
    ]
