# Generated by Django 5.1.3 on 2024-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
