# Generated by Django 5.1.3 on 2024-11-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_productcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
