# Generated by Django 5.1.3 on 2024-11-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_products_id_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product_id',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
