# Generated by Django 5.1.3 on 2024-11-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_productcategory_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='category_id',
        ),
    ]
