# Generated by Django 5.1.3 on 2024-11-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_product_id_productcategory_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='product_id',
        ),
    ]
