# Generated by Django 5.1.3 on 2024-11-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_product_id_productcategory_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='products',
            name='weightage_unit',
            field=models.CharField(blank=True, choices=[('ml', 'mililiter'), ('g', 'gram')], default='undefined', max_length=10),
        ),
    ]
