# Generated by Django 5.1.3 on 2024-11-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_products_weight_products_weightage_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_name',
            new_name='category',
        ),
    ]
